name: "update"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: unmojang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: 'echo "$UPSTREAM_KEY" > config/upstream.key'
      env:
        UPSTREAM_KEY: ${{ secrets.UPSTREAM_KEY }}
    - run: 'echo "$LAUNCHER_KEY" > config/launcher.key'
      env:
        LAUNCHER_KEY: ${{ secrets.LAUNCHER_KEY }}
    - run: ./clone.sh
    - run: nix develop --command bash -c 'poetry install && poetry run ./update.sh'
